TRAIN_DIR: ./train/pink121/
TEST_DIR: ./test/pink121/
bird: pink121

# spectral parameters
sr: 30000
NFFT: 256
data_window: 256
freq_range:
    - 300
    - 8000
n_tapers: 2
window_spacing: 100
window_len: 10
NW: 1.5

# target parameters
encoder:
    i: 1
    a: 2
    b: 3

# model parameters
test_data: pink121_test.npz
modelfile: pink121_model.h5
model: okanoya
syllable_class_weight: 2
batch_size: 500
n_epochs: 3
amplitude_norm: 100000

